### ISSUE TITLE
Node-RED Dashboard group / UI example

### ISSUE THREAD

**Issue by P1Rebo** [Paul-Reed/weather-icons#2]
Hi Paul,
first of all thank you for this nice icons library! I'm currently playing around with Node-RED and the UI / Dashboard package. Is there any complete UI Group / Template that you additionally could provide as an example. Actually your example [@[openenergymonitor.org]()](https://community.openenergymonitor.org/uploads/default/original/2X/0/08480b5d81803718382e6773d58ab7f8c8ca999d.PNG) looks great! Maybe you could provide the flow?

I'm planning to use the Dark Sky API for to build up my UI, since it's free and the weather predictions for Germany are OK.

Thank you very much in advance.
Cheers, Pedro

**Comment by Paul-Reed** [comment]
I'm afraid my flow integrates data obtained from Wunderground with my own data from outdoor weather sensors, therefore the flow wouldn't really export and import into other peoples dashboards. Also, as a lot of the code is javascript within template nodes, the api keys are hard coded.

Paul

**Comment by P1Rebo** [comment]
Thanks for the fast reply. As I saw Wunderground would also be great. Compared to my reference App the values seems to be accurate too!
If you could remove you API code it would be great. However, I understand if it's too much work for you.

Pedro

**Comment by Robert-Vaughan** [comment]
I'm using node-red, underground, and dashboard, but I'm having trouble showing the temperature on the UI gauge, as follows:
                                          -- debug (if I put msg.payload.tempf = correct temperature
inject -- wunderground -- gauge (won't show temperature).  

Please help?

**Comment by Paul-Reed** [comment]
This does not appear to be a weather-icons issue.
The node-red forum may be the best place to ask.
