### ISSUE TITLE
Path not found inside docker container of node-red

### ISSUE THREAD

**Issue by nicedevil007** [Paul-Reed/weather-icons#4]
Hey Paul,

can u give us a small guide how to install your awesome icons inside a docker environement?

I can't find this directory `.node-red/public`
I think the .node-red folder should be inside the /data folder for a docker environement.

I found the settings.js in this directory. But there is no public folder :(

**Comment by Paul-Reed** [comment]
As per this repo's readme, `weather-icons` has been retired in favour of `weather-icons-lite` which is now integrated into node-RED dashboard core.
